### JOB NAME
#PBS -N Selavy_spice
### Ask for email at job start, end, and if aborted
#PBS -M alec.thomson@anu.edu.au
#PBS -m abe
#### Ask for 1 total nodes, 3 ncpus instances
#PBS -l select=1:ncpus=28:mpiprocs=28
#PBS -l place=scatter:excl
#### Type of node: large memory
#PBS -q smallmem

cd /avatar/athomson/cubes/8585/RACS_test4_1.05_1049-31A/
mpirun -np 28 --verbose /priv/myrtle1/gaskap/nick/ASKAPsoft/Code/Components/Analysis/analysis/current/apps/selavy.sh -c /avatar/athomson/cubes/8585/RACS_test4_1.05_1049-31A/selavy_spice_test.in >> selavy.log
